/**
 * @module pandora-tools/contacts-tools
 * @description Tool definitions for Contacts + CRM Intelligence + Interactions
 */

export const contactsToolDefinitions = [
  { type: "function", function: { name: "add_contact", description: "Criar um novo contato", parameters: { type: "object", properties: { name: { type: "string" }, email: { type: "string" }, phone: { type: "string" }, company: { type: "string" }, role: { type: "string" }, tags: { type: "array", items: { type: "string" }, description: "Tags iniciais (opcional)" } }, required: ["name"], additionalProperties: false } } },
  { type: "function", function: { name: "edit_contact", description: "Editar um contato existente", parameters: { type: "object", properties: { contact_identifier: { type: "string" }, new_name: { type: "string" }, new_email: { type: "string" }, new_phone: { type: "string" }, new_company: { type: "string" }, new_role: { type: "string" } }, required: ["contact_identifier"], additionalProperties: false } } },
  { type: "function", function: { name: "delete_contact", description: "Excluir um contato pelo nome ou ID", parameters: { type: "object", properties: { contact_identifier: { type: "string" } }, required: ["contact_identifier"], additionalProperties: false } } },
  { type: "function", function: { name: "search_contacts", description: "Busca inteligente de contatos no banco COMPLETO. Busca por nome, e-mail, telefone, empresa, cargo ou tags.", parameters: { type: "object", properties: { query: { type: "string" } }, required: ["query"], additionalProperties: false } } },
  { type: "function", function: { name: "get_contacts", description: "Listar contatos com informações completas", parameters: { type: "object", properties: {}, additionalProperties: false } } },
  { type: "function", function: { name: "get_contact_details", description: "Ver detalhes COMPLETOS de um contato: info, tags, notas, aniversário, interações e WhatsApp. Use ANTES de enviar mensagens.", parameters: { type: "object", properties: { contact_identifier: { type: "string" } }, required: ["contact_identifier"], additionalProperties: false } } },
  { type: "function", function: { name: "smart_find_contact", description: "Busca inteligente no banco completo. Retorna até 10 resultados com indicação de WhatsApp.", parameters: { type: "object", properties: { query: { type: "string" } }, required: ["query"], additionalProperties: false } } },
  { type: "function", function: { name: "update_contact_tags", description: "Adicionar, substituir ou remover tags de um contato.", parameters: { type: "object", properties: { contact_identifier: { type: "string" }, tags: { type: "array", items: { type: "string" } }, mode: { type: "string", enum: ["replace", "add", "remove"] } }, required: ["contact_identifier", "tags"], additionalProperties: false } } },
  { type: "function", function: { name: "add_contact_note", description: "Adicionar uma nota/observação a um contato.", parameters: { type: "object", properties: { contact_identifier: { type: "string" }, note: { type: "string" } }, required: ["contact_identifier", "note"], additionalProperties: false } } },
  // CRM Intelligence
  { type: "function", function: { name: "favorite_contact", description: "Favoritar ou desfavoritar um contato", parameters: { type: "object", properties: { contact_identifier: { type: "string" }, favorite: { type: "boolean" } }, required: ["contact_identifier", "favorite"], additionalProperties: false } } },
  { type: "function", function: { name: "get_contact_stats", description: "Estatísticas avançadas do CRM: contatos por empresa, tag, tipo, interações recentes, cobertura de dados", parameters: { type: "object", properties: {}, additionalProperties: false } } },
  { type: "function", function: { name: "get_birthday_reminders", description: "Listar aniversários próximos dos contatos (próximos 30 dias)", parameters: { type: "object", properties: { days_ahead: { type: "number", description: "Dias à frente para buscar (padrão: 30)" } }, additionalProperties: false } } },
  { type: "function", function: { name: "bulk_tag_contacts", description: "Adicionar uma tag a múltiplos contatos de uma vez", parameters: { type: "object", properties: { contact_names: { type: "array", items: { type: "string" }, description: "Nomes dos contatos" }, tag: { type: "string", description: "Tag a adicionar" } }, required: ["contact_names", "tag"], additionalProperties: false } } },
  { type: "function", function: { name: "find_duplicate_contacts", description: "Encontrar contatos potencialmente duplicados por nome ou email", parameters: { type: "object", properties: {}, additionalProperties: false } } },
  // Interactions
  { type: "function", function: { name: "add_interaction", description: "Registrar interação com contato", parameters: { type: "object", properties: { contact_identifier: { type: "string" }, title: { type: "string" }, type: { type: "string", enum: ["meeting", "call", "email", "note", "whatsapp", "other"] }, description: { type: "string" } }, required: ["contact_identifier", "title", "type"], additionalProperties: false } } },
  { type: "function", function: { name: "get_interactions", description: "Listar interações de um contato", parameters: { type: "object", properties: { contact_identifier: { type: "string" }, limit: { type: "number" } }, required: ["contact_identifier"], additionalProperties: false } } },
];

export const contactsToolDefinitionsCompact = [
  { type: "function", function: { name: "add_contact", description: "Criar novo contato", parameters: { type: "object", properties: { name: { type: "string" }, email: { type: "string" }, phone: { type: "string" }, company: { type: "string" }, role: { type: "string" } }, required: ["name"], additionalProperties: false } } },
  { type: "function", function: { name: "edit_contact", description: "Editar contato existente", parameters: { type: "object", properties: { contact_identifier: { type: "string" }, new_name: { type: "string" }, new_email: { type: "string" }, new_phone: { type: "string" }, new_company: { type: "string" }, new_role: { type: "string" } }, required: ["contact_identifier"], additionalProperties: false } } },
  { type: "function", function: { name: "delete_contact", description: "Excluir contato", parameters: { type: "object", properties: { contact_identifier: { type: "string" } }, required: ["contact_identifier"], additionalProperties: false } } },
  { type: "function", function: { name: "get_contacts", description: "Listar contatos do usuário", parameters: { type: "object", properties: {}, additionalProperties: false } } },
  { type: "function", function: { name: "search_contacts", description: "Buscar contatos por nome, email, telefone ou empresa", parameters: { type: "object", properties: { query: { type: "string" } }, required: ["query"], additionalProperties: false } } },
  { type: "function", function: { name: "get_contact_details", description: "Detalhes completos de um contato", parameters: { type: "object", properties: { contact_identifier: { type: "string" } }, required: ["contact_identifier"], additionalProperties: false } } },
  { type: "function", function: { name: "smart_find_contact", description: "Busca inteligente no banco completo de contatos", parameters: { type: "object", properties: { query: { type: "string" } }, required: ["query"], additionalProperties: false } } },
  { type: "function", function: { name: "add_contact_note", description: "Adicionar nota a um contato", parameters: { type: "object", properties: { contact_identifier: { type: "string" }, note: { type: "string" } }, required: ["contact_identifier", "note"], additionalProperties: false } } },
  { type: "function", function: { name: "update_contact_tags", description: "Atualizar tags de um contato", parameters: { type: "object", properties: { contact_identifier: { type: "string" }, tags: { type: "array", items: { type: "string" } }, mode: { type: "string", enum: ["replace", "add", "remove"] } }, required: ["contact_identifier", "tags"], additionalProperties: false } } },
  { type: "function", function: { name: "add_interaction", description: "Registrar interação com contato", parameters: { type: "object", properties: { contact_identifier: { type: "string" }, title: { type: "string" }, type: { type: "string", enum: ["meeting", "call", "email", "note", "whatsapp", "other"] }, description: { type: "string" } }, required: ["contact_identifier", "title", "type"], additionalProperties: false } } },
  { type: "function", function: { name: "get_interactions", description: "Listar interações recentes de um contato", parameters: { type: "object", properties: { contact_identifier: { type: "string" }, limit: { type: "number" } }, required: ["contact_identifier"], additionalProperties: false } } },
];
