/**
 * @module pandora-tools/finance-tools
 * @description Tool definitions for Finances, Goals, Recurring, Budgets, Analytics, Open Banking
 */

export const financeToolDefinitions = [
  // Transactions
  { type: "function", function: { name: "add_finance_transaction", description: "Registrar uma transação financeira", parameters: { type: "object", properties: { description: { type: "string" }, amount: { type: "number" }, type: { type: "string", enum: ["income", "expense"] }, category: { type: "string" }, date: { type: "string", description: "Data da transação (YYYY-MM-DD, opcional, padrão: hoje)" } }, required: ["description", "amount", "type"], additionalProperties: false } } },
  { type: "function", function: { name: "delete_finance_transaction", description: "Excluir transação financeira", parameters: { type: "object", properties: { transaction_identifier: { type: "string" } }, required: ["transaction_identifier"], additionalProperties: false } } },
  { type: "function", function: { name: "edit_finance_transaction", description: "Editar transação financeira", parameters: { type: "object", properties: { transaction_identifier: { type: "string" }, new_description: { type: "string" }, new_amount: { type: "number" }, new_category: { type: "string" }, new_type: { type: "string", enum: ["income", "expense"] } }, required: ["transaction_identifier"], additionalProperties: false } } },
  { type: "function", function: { name: "get_recent_transactions", description: "Listar transações recentes com detalhes", parameters: { type: "object", properties: { limit: { type: "number" }, type_filter: { type: "string", enum: ["income", "expense", "all"] } }, additionalProperties: false } } },
  // Summary
  { type: "function", function: { name: "get_finance_summary", description: "Resumo financeiro com opção de período", parameters: { type: "object", properties: { period: { type: "string", enum: ["today", "week", "month", "year", "all"], description: "Período (padrão: month)" } }, additionalProperties: false } } },
  { type: "function", function: { name: "get_category_stats", description: "Estatísticas de gastos por categoria no período", parameters: { type: "object", properties: { period: { type: "string", enum: ["week", "month", "year"], description: "Período (padrão: month)" }, type_filter: { type: "string", enum: ["income", "expense", "all"] } }, additionalProperties: false } } },
  // Goals
  { type: "function", function: { name: "add_finance_goal", description: "Criar uma meta financeira", parameters: { type: "object", properties: { name: { type: "string" }, target: { type: "number" }, current: { type: "number" } }, required: ["name", "target"], additionalProperties: false } } },
  { type: "function", function: { name: "update_finance_goal", description: "Atualizar o progresso de uma meta financeira", parameters: { type: "object", properties: { goal_identifier: { type: "string" }, new_current: { type: "number" } }, required: ["goal_identifier", "new_current"], additionalProperties: false } } },
  { type: "function", function: { name: "get_finance_goals", description: "Listar metas financeiras", parameters: { type: "object", properties: {}, additionalProperties: false } } },
  // Recurring
  { type: "function", function: { name: "add_finance_recurring", description: "Criar recorrência mensal", parameters: { type: "object", properties: { description: { type: "string" }, amount: { type: "number" }, type: { type: "string", enum: ["income", "expense"] }, category: { type: "string" }, day_of_month: { type: "number" } }, required: ["description", "amount", "type"], additionalProperties: false } } },
  { type: "function", function: { name: "delete_finance_recurring", description: "Excluir recorrência", parameters: { type: "object", properties: { recurring_identifier: { type: "string" } }, required: ["recurring_identifier"], additionalProperties: false } } },
  { type: "function", function: { name: "toggle_finance_recurring", description: "Ativar/desativar recorrência", parameters: { type: "object", properties: { recurring_identifier: { type: "string" }, active: { type: "boolean" } }, required: ["recurring_identifier", "active"], additionalProperties: false } } },
  { type: "function", function: { name: "get_finance_recurring", description: "Listar recorrências financeiras", parameters: { type: "object", properties: {}, additionalProperties: false } } },
  // Budgets
  { type: "function", function: { name: "add_budget", description: "Criar orçamento mensal para categoria", parameters: { type: "object", properties: { category: { type: "string" }, monthly_limit: { type: "number" } }, required: ["category", "monthly_limit"], additionalProperties: false } } },
  { type: "function", function: { name: "get_budgets", description: "Listar orçamentos e status de uso", parameters: { type: "object", properties: {}, additionalProperties: false } } },
  { type: "function", function: { name: "delete_budget", description: "Excluir orçamento", parameters: { type: "object", properties: { budget_identifier: { type: "string" } }, required: ["budget_identifier"], additionalProperties: false } } },
  { type: "function", function: { name: "edit_budget", description: "Alterar limite de orçamento", parameters: { type: "object", properties: { budget_identifier: { type: "string" }, new_monthly_limit: { type: "number" } }, required: ["budget_identifier", "new_monthly_limit"], additionalProperties: false } } },
  // Analytics
  { type: "function", function: { name: "analyze_spending_patterns", description: "Análise inteligente de padrões de gasto: tendências, anomalias, previsões. Identifica gastos acima da média, categorias em crescimento e oportunidades de economia.", parameters: { type: "object", properties: { months: { type: "number", description: "Quantos meses analisar (padrão: 3)" } }, additionalProperties: false } } },
  { type: "function", function: { name: "compare_periods", description: "Comparar dois períodos financeiros lado a lado (ex: este mês vs mês passado, este trimestre vs anterior)", parameters: { type: "object", properties: { period_type: { type: "string", enum: ["month", "quarter", "year"], description: "Tipo de período" }, offset: { type: "number", description: "Quantos períodos atrás comparar (padrão: 1)" } }, additionalProperties: false } } },
  { type: "function", function: { name: "goal_projections", description: "Projetar quando metas financeiras serão atingidas com base no ritmo atual de economia/contribuição", parameters: { type: "object", properties: {}, additionalProperties: false } } },
  // Open Banking (Pluggy)
  { type: "function", function: { name: "get_bank_accounts", description: "Listar contas bancárias conectadas via Open Banking (saldo, tipo, banco)", parameters: { type: "object", properties: {}, additionalProperties: false } } },
  { type: "function", function: { name: "get_investments", description: "Listar investimentos do portfólio (ações, fundos, renda fixa, crypto)", parameters: { type: "object", properties: {}, additionalProperties: false } } },
  { type: "function", function: { name: "get_financial_connections", description: "Listar bancos e instituições financeiras conectados", parameters: { type: "object", properties: {}, additionalProperties: false } } },
  { type: "function", function: { name: "get_bank_transactions", description: "Listar transações reais de contas bancárias conectadas (Open Banking)", parameters: { type: "object", properties: { account_id: { type: "string", description: "ID da conta (opcional — se omitido, mostra todas)" }, limit: { type: "number", description: "Número de transações (padrão: 20)" } }, additionalProperties: false } } },
];

export const financeToolDefinitionsCompact = [
  { type: "function", function: { name: "add_finance_transaction", description: "Registrar transação financeira", parameters: { type: "object", properties: { description: { type: "string" }, amount: { type: "number" }, type: { type: "string", enum: ["income", "expense"] }, category: { type: "string" } }, required: ["description", "amount", "type"], additionalProperties: false } } },
  { type: "function", function: { name: "get_finance_summary", description: "Resumo financeiro do mês", parameters: { type: "object", properties: {}, additionalProperties: false } } },
  { type: "function", function: { name: "get_finance_goals", description: "Listar metas financeiras", parameters: { type: "object", properties: {}, additionalProperties: false } } },
  { type: "function", function: { name: "add_finance_goal", description: "Criar meta financeira", parameters: { type: "object", properties: { name: { type: "string" }, target: { type: "number" }, current: { type: "number" } }, required: ["name", "target"], additionalProperties: false } } },
  { type: "function", function: { name: "update_finance_goal", description: "Atualizar progresso de uma meta financeira", parameters: { type: "object", properties: { goal_identifier: { type: "string" }, new_current: { type: "number" } }, required: ["goal_identifier", "new_current"], additionalProperties: false } } },
  { type: "function", function: { name: "add_finance_recurring", description: "Criar recorrência financeira mensal", parameters: { type: "object", properties: { description: { type: "string" }, amount: { type: "number" }, type: { type: "string", enum: ["income", "expense"] }, category: { type: "string" }, day_of_month: { type: "number" } }, required: ["description", "amount", "type"], additionalProperties: false } } },
  { type: "function", function: { name: "delete_finance_recurring", description: "Excluir recorrência financeira", parameters: { type: "object", properties: { recurring_identifier: { type: "string" } }, required: ["recurring_identifier"], additionalProperties: false } } },
  { type: "function", function: { name: "toggle_finance_recurring", description: "Ativar ou desativar recorrência financeira", parameters: { type: "object", properties: { recurring_identifier: { type: "string" }, active: { type: "boolean" } }, required: ["recurring_identifier", "active"], additionalProperties: false } } },
  { type: "function", function: { name: "get_finance_recurring", description: "Listar recorrências financeiras", parameters: { type: "object", properties: {}, additionalProperties: false } } },
  { type: "function", function: { name: "get_recent_transactions", description: "Listar transações financeiras recentes", parameters: { type: "object", properties: { limit: { type: "number" }, type_filter: { type: "string", enum: ["income", "expense", "all"] } }, additionalProperties: false } } },
  { type: "function", function: { name: "add_budget", description: "Criar orçamento mensal para uma categoria", parameters: { type: "object", properties: { category: { type: "string" }, monthly_limit: { type: "number" } }, required: ["category", "monthly_limit"], additionalProperties: false } } },
  { type: "function", function: { name: "get_budgets", description: "Listar orçamentos mensais", parameters: { type: "object", properties: {}, additionalProperties: false } } },
];
