export const ROUTES = {
  HOME: "/dashboard",
  AUTH: "/auth",
  PRIVACY: "/privacy",
  TERMS: "/terms",
  CONNECTIONS: "/integrations",
  SEARCH: "/search",
  CALENDAR: "/calendar",
  WIDGETS: "/widgets",
  SETTINGS: "/settings",
  PROFILE: "/profile",
  ADMIN: "/admin",
  EMAIL: "/email",
  MESSAGES: "/messages",
  FILES: "/files",
  NOTES: "/notes",
  TASKS: "/tasks",
  CONTACTS: "/contacts",
  FINANCES: "/finances",
  AI: "/ai",
  NOTIFICATIONS: "/notifications",
  INBOX: "/inbox",
  AUTOMATIONS: "/automations",
  WHATSAPP_SETTINGS: "/settings/whatsapp",
  PRICING: "/pricing",
  BILLING: "/billing",
  ACTIVITY_LOGS: "/settings/logs",
  DATA_RESET: "/settings/data-reset",
  WELCOME: "/welcome",
  WORKSPACES: "/workspaces",
  SOCIAL: "/social",
} as const;

export type RoutePath = (typeof ROUTES)[keyof typeof ROUTES];
